# generated by datamodel-codegen:
#   filename:  https://stac-extensions.github.io/scientific/v1.0.0/schema.json
#   timestamp: 2023-03-21T11:25:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Extra, Field, constr


class ScientificCitationExtensionItem2(BaseModel):
    assets: Dict[str, Any]


class ScientificCitationExtensionItem3(BaseModel):
    item_assets: Dict[str, Any]


class StacExtensions(BaseModel):
    stac_extensions: List


class RequireAnyField(BaseModel):
    __root__: Union[Any, Any, Any]


class SciPublication(BaseModel):
    doi: Optional[constr(regex=r'^10\.[0-9a-zA-Z]{4,}/[^\s]+$')] = Field(
        None, title='Publication DOI'
    )
    citation: Optional[str] = Field(None, title='Publication Citation')


class Fields(BaseModel):
    class Config:
        extra = Extra.forbid

    sci_doi: Optional[constr(regex=r'^10\.[0-9a-zA-Z]{4,}/[^\s]+$')] = Field(
        None, alias='sci:doi', title='Data DOI'
    )
    sci_citation: Optional[str] = Field(
        None, alias='sci:citation', title='Proposed Data Citation'
    )
    sci_publications: Optional[List[SciPublication]] = Field(
        None, alias='sci:publications', title='Publications'
    )


class Properties(Fields):
    pass


class ScientificCitationExtensionItem(StacExtensions):
    type: Any
    properties: Properties
    assets: Dict[str, Fields]


class ScientificCitationExtensionItem1(Fields):
    pass


class ScientificCitationExtensionItem4(BaseModel):
    summaries: RequireAnyField


class ScientificCitationExtension(BaseModel):
    __root__: Union[
        ScientificCitationExtensionItem,
        Union[
            ScientificCitationExtensionItem1,
            ScientificCitationExtensionItem2,
            ScientificCitationExtensionItem3,
            ScientificCitationExtensionItem4,
        ],
    ] = Field(
        ...,
        description='Scientific Citation Extension for STAC Items and STAC Collections.',
        title='Scientific Citation Extension',
    )
