# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/thareUSGS/ssys/main/json-schema/schema.json
#   timestamp: 2023-03-21T11:47:23+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field


class StacExtensions(BaseModel):
    stac_extensions: List


class Ssys(BaseModel):
    ssys_targets: Optional[List[str]] = Field(None, alias='ssys:targets', min_items=1)


class SsysExtensionItem(StacExtensions):
    type: Any
    properties: Ssys
    assets: Dict[str, Ssys]


class SsysExtensionItem1(StacExtensions, Ssys):
    type: Any
    assets: Optional[Dict[str, Ssys]] = None
    item_assets: Optional[Dict[str, Ssys]] = None


class SsysExtensionItem2(StacExtensions, Ssys):
    type: Any
    assets: Optional[Dict[str, Ssys]] = None
    item_assets: Optional[Dict[str, Ssys]] = None


class SsysExtension(BaseModel):
    __root__: Union[SsysExtensionItem, SsysExtensionItem1, SsysExtensionItem2] = Field(
        ...,
        description='STAC SSYS Extension for STAC Items, Catalogs, or Collections.',
        title='SSYS Extension',
    )
